### ISSUE TITLE
do not start after install in debian 11

### ISSUE THREAD

**Issue by joluruba** [canonical/mir-kiosk-kodi#34]
hello, thanks for your job, i have install this snap in my debian 11, but when i try to start the snap. it show the follow  error:
WARNING: network-observe interface not connected! Please run: /snap/mir-kiosk-kodi/current/bin/setup.sh

and after i execute this:  /snap/mir-kiosk-kodi/current/bin/setup.sh 
the snap show this:

Setting up watches.
Watches established.
 
and nothing more happend.
¿Any idea what is wrong?

**Comment by AlanGriffiths** [comment]
Nothing is wrong, it is waiting for a Wayland compositor to start

**Comment by joluruba** [comment]
But my linux work fine, Is there any necessary requirement, for it to work this snap ?

**Comment by AlanGriffiths** [comment]
Yes, it needs a Wayland compositor: Principally [Ubuntu Frame](https://snapcraft.io/ubuntu-frame). But GNOME/Wayland (for example also works)

I can see that the [mir-kiosk-kodi](https://github.com/MirServer/mir-kiosk-kodi) description doesn't make this clear and needs updating. (I'll do that later today)

Are you interested in this specific snap, which is designed for an embedded environment?

Or are you trying to use Kodi on an X11 desktop environment? In that case, you might simply want to install from archive, or from the team-xbmc PPA.

**Comment by joluruba** [comment]
Thanks, for your time, currently Iam using kodi on an X11 desktop environment with mate, but I have some problems with some plugins like Luar and Palantir2, then im looking for an alternative for sulition this, for this im using this snap but I have the problem described in this post.
If i use Mate, what i need to install???

**Comment by AlanGriffiths** [comment]
I don't know anything about the state of Kodi in Debian, so I can't help with that.

I don't think MATE supports Wayland at present (although many of [it's desktop components do already](https://discourse.ubuntu.com/t/what-i-did-on-my-vacation/29552/2))

The simplest way of getting this snap running on an X11 environment:

```
snap install --classic frame-it
snap install ubuntu-frame
frame-it mir-kiosk-kodi
```

But none of this is a problem with mir-kiosk-kodi, so I'll close the issue
