### ISSUE TITLE
Ubuntu desktop usage

### ISSUE THREAD

**Issue by amodster** [canonical/mir-kiosk-kodi#38]
Hello
How to start the Kodi GUI ?

I installed kodi ( sudo snap install mir-kiosk-kodi ) onto Ubuntu 22.04 desktop. and enabled the daemon ( snap set mir-kiosk-kodi daemon=true ).
Wayland should already be running for this version of Ubuntu.

Thanks

**Comment by amodster** [comment]
I found the application start for kodi

But now it crashes, see attached crash log.
[kodi_crashlog-20230608_172305.log](https://github.com/MirServer/mir-kiosk-kodi/files/11698876/kodi_crashlog-20230608_172305.log)

**Comment by Saviq** [comment]
@amodster if you want it to run as a daemon, you also need a Wayland compositor running as root, try this:

https://mir-server.io/docs/run-ubuntu-frame-on-your-device

On your desktop, just start `mir-kiosk-kodi`, but unless you're actually interested in running it as a daemon, you may be better off with the debs.

I'll close for now, will reopen if we find something is actually wrong.
