### ISSUE TITLE
Deamon errors using Ubuntu Core

### ISSUE THREAD

**Issue by amodster** [canonical/mir-kiosk-kodi#39]
Hello
KODI daemon crash during startup.

Ubuntu Core 22.04
RPI

Attached are the crash log and kodi log, and my setup file.

Thanks
[kodi-20230707.log](https://github.com/MirServer/mir-kiosk-k
[kodi_crashlog-20230707_020520.log](https://github.com/MirServer/mir-kiosk-kodi/files/11974123/kodi_crashlog-20230707_020520.log)
[readme-20230706.txt](https://github.com/MirServer/mir-kiosk-kodi/files/11974124/readme-20230706.txt)

odi/files/11974122/kodi-20230707.log)

**Comment by amodster** [comment]
Not sure it made it
[kodi-20230707.log](https://github.com/MirServer/mir-kiosk-kodi/files/11974154/kodi-20230707.log)

**Comment by Saviq** [comment]
@amodster what does `snap connections mir-kiosk-kodi` say? Did you install e.g. (Ubuntu Frame)[https://snapcraft.io/ubuntu-frame/) to run as the display server?

**Comment by AlanGriffiths** [comment]
Not enough information to reproduce
